### ISSUE TITLE
Problem: this project can't replace RDSS's fork yet

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1127]
RDSS wants to switch to vanilla AM but it can't because the issues listed below haven't been addressed yet.

Similar issue in SS: https://github.com/artefactual/archivematica-storage-service/issues/375.

Dependencies:
- [x] Parent to #1124 (PR #1154).
- [x] Parent to #1128 (PR #813).
- [x] Parent to #1130 (PR #1155).
- [x] Parent to #1131 (PR #1165).
- [x] Parent to #1132 (PR #1168).
- [x] Parent to #1134 (PR #1165).
- [x] Parent to #1135 (PR #1167).
- [x] Parent to #1138 (PR #1166).
- [x] Parent to #1140 (PR #1142).
- [x] Parent to #1133 (PR #1170).
- [x] Parent to #1136 (PR #1190).
- [x] Parent to #1139 (PR #1191).
- [x] Parent to #1192 (PR #1193).

Lower priority:
- [ ] Parent to #1137 - not in AM18 roadmap yet.
- [ ] Parent to #1129 (PR #1169) - needs more work.

Related: https://jiscdev.atlassian.net/browse/RDSSARK-521.
Fork's address: https://github.com/JiscRDSS/archivematica.

**Comment by joel-simpson** [comment]
Regarding RDSS version number (JiscRDSS#48, JiscRDSS#51) 
I agree, since the goal is for Jisc to be able to replace their fork with the public release of Archivematica, the RDSS version number is not as important as it was. 
However, the RDSS version number is associated with the rdss-archivematica repo, which is a sort of 'distribution repo'. An RDSS version number is associated with a version number for each component; including Archivematica, the storage service, channel adapter, NextCloud and others. This is very useful for a managed service provider with many deployments. 
It could well be an acceptable trade-off to lose this (as part of migrating back to the public release and not having a Jisc fork). 
On the other hand, if we could find a way to include both version numbers, I think it could benefit many other users. Perhaps it would be possible to have an optional "distribution version number" (or "deployment" or similar)? This wouldn't even need to be used in the METS as an agent, and could be purely for support purposes.
